name: totsparis2
description: A new Flutter project.
version: 1.0.0+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icon/
