name: totsparis2
description: A new Flutter project.
version: 1.0.0+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.4.2
  onesignal_flutter: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icon/
